[package]
name = "flluf-lang"
version = "0.2.0"
edition = "2024"

[[bin]]
name = "flluf"
path = "src/main.rs"

[dependencies]
cranelift = "0.134"
cranelift-module = "0.134"
cranelift-object = "0.134"
cranelift-frontend = "0.134"
cranelift-native = "0.134"
anyhow = "1"
clap = { version = "4", features = ["derive"] }
toml = "1.1"
